import {test, expect} from '@playwright/test'
import {receivablesFixture} from './fixtures/receivables'

test('amount-first team/person cascade uses IDs and resets child before requesting the new team', async ({page}) => {
  const requests = await receivablesFixture(page)
  await page.getByRole('navigation').getByRole('button', {name: /应收款跟进/}).click()
  const report = page.getByRole('region', {name: '收款统计与客户台账'})
  const group = report.getByRole('combobox', {name: '业务团队', exact: true})
  const person = report.getByRole('combobox', {name: '人员范围', exact: true})
  await expect(group).toBeEnabled()
  const amount = report.getByRole('button', {name: /未收款总额/})
  expect((await amount.boundingBox())!.y).toBeLessThan((await group.boundingBox())!.y)
  await group.selectOption('g1')
  await expect(person.locator('option')).toHaveText(['该团队全部负责人', '坐席甲'])
  await person.selectOption('id:seat1')
  await expect(amount).toContainText('280.00')
  await group.selectOption('g11')
  await expect(person).toHaveValue('all')
  await expect(person.locator('option')).toHaveText(['该团队全部负责人', '坐席乙'])
  await expect(amount).toContainText('100.00')
  await amount.click()
  const details = report.getByRole('region', {name: '对应任务明细'})
  await expect(details.locator('tbody tr')).toHaveCount(1)
  await expect(details).toContainText('明日测试群')
  const request = requests.filter(url => url.pathname === '/api/receivables-report').at(-1)!
  expect(request.searchParams.get('group_id')).toBe('g11')
  expect(request.searchParams.get('owner')).toBe('all')
  expect(request.searchParams.has('team')).toBe(false)
})

test('explicit terminal status opens history and returning to current clears that contradictory status', async ({page}) => {
  await receivablesFixture(page)
  await page.getByRole('navigation').getByRole('button', {name: /应收款跟进/}).click()
  const report = page.getByRole('region', {name: '收款统计与客户台账'})
  await report.getByRole('combobox', {name: '状态', exact: true}).selectOption('closed')
  await report.getByRole('button', {name: '查询', exact: true}).click()
  const details = report.getByRole('region', {name: '对应任务明细'})
  await expect(details.locator('tbody tr')).toHaveCount(1)
  await expect(details).toContainText('历史测试群')
  await report.getByRole('button', {name: '当前跟进', exact: true}).click()
  await expect(report.getByRole('combobox', {name: '状态', exact: true})).toHaveValue('all')
  await expect(details.locator('tbody tr')).toHaveCount(3)
})

test('creation is a focused task, retains draft on close, and untouched required fields are not invalid', async ({page}) => {
  await receivablesFixture(page)
  await page.getByRole('navigation').getByRole('button', {name: /应收款跟进/}).click()
  await page.getByRole('button', {name: '新建应收款', exact: true}).click()
  const dialog = page.getByRole('dialog', {name: '新建应收款'})
  await expect(dialog.locator('[aria-invalid=true]')).toHaveCount(0)
  const subject = dialog.getByRole('textbox', {name: '业务对象 / 群名称', exact: true})
  await subject.fill('保留的草稿')
  await page.keyboard.press('Escape')
  await page.getByRole('button', {name: '新建应收款', exact: true}).click()
  await expect(subject).toHaveValue('保留的草稿')
  await expect(dialog.getByRole('combobox', {name: '业务团队', exact: true})).toBeVisible()
})
