import { expect, test, type Locator, type Page } from '@playwright/test'
test.use({actionTimeout:10000})

import { uiFixture as fixture } from './fixtures/ui'

async function visibleControl(control: Locator) {
  await expect(control).toBeVisible()
  const style = await control.evaluate(el => {
    const s=getComputedStyle(el)
    return {height:el.getBoundingClientRect().height,border:s.borderTopWidth,bg:s.backgroundColor,opacity:s.opacity}
  })
  expect(style.height).toBeGreaterThanOrEqual(40)
  expect(style.border).toBe('1px')
  expect(style.bg).not.toBe('rgba(0, 0, 0, 0)')
  expect(style.opacity).toBe('1')
}

for (const viewport of [{width:1366,height:768},{width:1920,height:1080},{width:960,height:540}]) {
  test(`audited inputs remain discoverable at ${viewport.width} CSS pixels`,async({page},info)=>{
    await page.setViewportSize(viewport)
    const writes=await fixture(page)
    const nav=page.getByRole('navigation')
    await nav.getByRole('button',{name:/提醒中心/}).click()
    await expect(page.getByRole('heading',{name:'统一任务收件箱'})).toBeVisible()
    await page.getByRole('button',{name:'新建提醒',exact:true}).click()
    await page.getByRole('button',{name:'手动填写',exact:true}).click()
    await visibleControl(page.getByLabel('个人提醒事项',{exact:true}))
    await visibleControl(page.getByLabel('个人提醒日期',{exact:true}))
    await visibleControl(page.getByLabel('个人提醒时间',{exact:true}))
    await page.getByLabel('个人提醒事项',{exact:true}).focus()
    expect(await page.getByLabel('个人提醒事项',{exact:true}).evaluate(el=>getComputedStyle(el).outlineStyle)).toBe('solid')
    await page.screenshot({path:info.outputPath('reminder-controls.png'),fullPage:true})
    await page.getByRole('button',{name:'AI 整理',exact:true}).click()
    await visibleControl(page.getByLabel('提醒要求',{exact:true}))
    await visibleControl(page.getByLabel('我的默认班次',{exact:true}))
    await page.getByRole('button',{name:'通知设置与记录',exact:true}).click()
    expect(await page.getByRole('slider').evaluate(el=>el.getBoundingClientRect().height)).toBeLessThan(42)
    await nav.getByRole('button',{name:/逾期未处理/}).click()
    const search=page.getByRole('textbox',{name:'搜索业务对象或群名称'})
    await expect(search).toBeVisible()
    expect(await search.locator('..').evaluate(el=>getComputedStyle(el).opacity)).toBe('1')
    await search.fill('无匹配'); await search.locator('..').getByRole('button').click()
    await expect(search).toHaveValue('')
    await nav.getByRole('button',{name:/员工与权限/}).click()
    await expect(page.getByRole('heading',{name:'员工与权限',exact:true})).toBeVisible()
    await page.getByRole('tab',{name:'组别',exact:true}).click()
    await visibleControl(page.getByLabel('新增组别名称',{exact:true}))
    await visibleControl(page.getByLabel('新增组别负责人',{exact:true}))
    await visibleControl(page.getByLabel('测试组名称',{exact:true}))
    await expect(page.getByText('编辑组名',{exact:true})).toBeVisible()
    await expect(page.getByRole('button',{name:'删除组别',exact:true})).toBeDisabled()
    await page.getByRole('tab',{name:'员工',exact:true}).click()
    await page.locator('summary').filter({hasText:'开通员工账号'}).click()
    await visibleControl(page.getByRole('combobox',{name:'员工角色',exact:true}))
    await nav.getByRole('button',{name:/AI模型配置/}).click()
    await page.getByTestId('answer-configuration-disclosure').locator('summary').first().click()
    await page.getByRole('button',{name:'新增回答模型',exact:true}).click()
    await visibleControl(page.getByRole('combobox',{name:'AI 厂商',exact:true}))
    await page.getByRole('tab',{name:'知识检索',exact:true}).click()
    await page.getByRole('tabpanel').locator('summary').filter({hasText:'编辑知识检索配置'}).click()
    await visibleControl(page.getByRole('combobox',{name:'向量厂商',exact:true}))
    await page.getByRole('tab',{name:'人设',exact:true}).click()
    await visibleControl(page.getByLabel('人设设定',{exact:true}))
    for(const input of await page.locator('input[type=password]').all()) {
      await expect(input).toHaveAttribute('type','password')
      await expect(input).toHaveValue('')
    }
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
    await page.screenshot({path:info.outputPath('model-controls.png'),fullPage:true})
    expect(writes).toEqual([])
  })
}

test('knowledge selection is neutral, review textarea visible and deletion still confirms',async({page})=>{
  const writes=await fixture(page)
  await page.getByRole('navigation').getByRole('button',{name:/企业知识/}).click()
  await expect(page.getByText('选择此知识',{exact:true})).toBeVisible()
  await expect(page.getByText('加入批量删除',{exact:true})).toHaveCount(0)
  await visibleControl(page.getByLabel('审核说明',{exact:true}))
  await page.getByRole('checkbox',{name:/选择 测试知识/}).check()
  await expect(page.getByRole('button',{name:'审核并发布所选（1）'})).toBeEnabled()
  expect(writes).toEqual([])
  await page.getByRole('button',{name:'批量删除（1）'}).click()
  await expect(page.getByText(/确认永久删除所选 1 条知识/)).toBeVisible()
  await page.getByRole('button',{name:'取消',exact:true}).click()
  expect(writes).toEqual([])
})

test('invalid password and receivable fields explain why submit is disabled without writes',async({page})=>{
  const writes=await fixture(page)
  await page.getByRole('button',{name:'账户安全',exact:true}).click()
  const current=page.getByLabel('当前密码',{exact:true}), password=page.getByLabel('新密码',{exact:true}), confirm=page.getByLabel('确认新密码',{exact:true})
  await current.fill('fixture-old')
  await password.fill('short')
  await confirm.fill('different')
  await expect(password).toHaveAttribute('aria-invalid','true')
  await expect(confirm).toHaveAttribute('aria-invalid','true')
  await expect(password).toHaveAccessibleDescription(/至少 6 位/)
  await password.fill('fixture-new');await confirm.fill('fixture-new')
  await expect(password).not.toHaveAttribute('aria-invalid','true')
  await expect(confirm).not.toHaveAttribute('aria-invalid','true')
  await page.keyboard.press('Escape')
  await page.getByRole('navigation').getByRole('button',{name:/应收款跟进/}).click()
  await page.getByRole('button',{name:'新建应收款',exact:true}).click()
  const form=page.locator('.web-create-receivable')
  await expect(form.getByRole('heading',{name:'新建应收款'})).toBeVisible()
  const amount=form.getByLabel('应收金额（元）',{exact:true})
  await amount.fill('12.345')
  await amount.blur()
  await expect(amount).toHaveAttribute('aria-invalid','true')
  await expect(amount).toHaveAccessibleDescription(/最多两位小数/)
  await amount.fill('12.34')
  await form.getByLabel('业务对象 / 群名称',{exact:true}).fill('仅测试不提交')
  await form.getByLabel('预计到账日期',{exact:true}).fill('2027-01-01')
  await expect(form.getByRole('button',{name:'创建应收款',exact:true})).toBeEnabled()
  await expect(amount).not.toHaveAttribute('aria-invalid','true')
  expect(writes).toEqual([])
})
