import { useI18n } from '@/i18n/context'

const zh = {
  reminderCueTitle: '待办提醒',
  reminderRepeatPrefix: '30 分钟未更新，请继续跟进 · ',
  reminderRepeatHint: '首次提醒后，状态未更新将在 30 分钟后补提醒一次。客户端需保持运行并连接服务器。',
  reminderSoundTest: '试听提醒音',
  reminderSoundFailed: '提示音未播放，请检查音量和音频设备后试听。文字提醒不受影响。',
  copyReply: '点击复制',
  replyCopied: '已复制',
  replyCopyFailed: '复制失败，请选中文字后复制',
  suggestedReply: '回答建议',
  currentReply: '当前回复话术',
  followupReply: '继续跟进话术',
  alternativeReply: '备选回答',
  account: '账户安全',
  password: '修改密码',
  logout: '退出登录',
  close: '关闭',
  cancel: '取消',
  save: '保存',
  refresh: '刷新',
  currentPassword: '当前密码',
  newPassword: '新密码',
  confirmPassword: '确认新密码',
  passwordHint: '新密码至少 6 位，且不能与当前密码相同。修改后本机保存的旧密码会清除，请在下次登录时重新勾选记住密码。',
  passwordSaved: '密码已修改，当前会话已更新。',
  logoutHint: '退出会清除当前会话和本机记住的登录信息。请先保存未提交内容。',
  working: '正在处理…',
  failed: '操作未完成，请检查连接和权限后重试。',
  unavailable: '服务端尚未启用此功能。',
  dirty: '有未保存内容或正在执行的操作，请完成或清空后更新。',
  empty: '暂无记录。',
  loading: '正在读取记录…',
  followups: '应收款跟进',
  create: '新建',
  personalFollowups: '我创建的应收款',
  subject: '业务对象 / 群名称',
  team: '业务团队',
  amount: '应收金额（元）',
  receivableDate: '应收日期',
  expectedDate: '预计到账日期',
  created: '已创建，提醒已同步到提醒中心。',
  followupHint: '记录实际应收款，由服务端建立后续提醒；企微通知需要本人已完成企微绑定。',
  inspect: '查看与处理',
  status: '状态',
  retryHint: '未确认提交结果。保留本次请求，请先刷新列表；重试同一请求不会重复创建。',
  retrySubmit: '重试提交',
  resetDraft: '清空草稿',
  abandon: '放弃本次重试',
  abandonHint: '放弃只会清空本机草稿，不撤销可能已创建的记录。重新新建前，请先在列表核对，避免重复。',
  previous: '上一页',
  next: '下一页',
  submitted: '已提交',
  pending: '待处理',
  paid: '已收款',
  cancelled: '已取消',
  closed: '已关闭',
  waiting: '等待更新',
  history: '提醒触发历史',
  deliveries: '通知投递记录',
  time: '时间',
  channel: '渠道',
  attempts: '尝试次数',
  error: '错误类别',
  nextRetry: '下次重试',
  historyHint: '触发记录与通知送达是两个阶段；这里不将已触发显示为已送达。',
  uploads: '历史上传',
  resume: '继续处理',
  rechunk: '重新切分',
  chunkSize: '每块字符数',
  overlap: '重叠字符数',
  rechunkHint: '重新切分会替换当前上传批次的未提交分块，请先保存需要保留的编辑。已提交或发布的批次由服务器拒绝修改。',
  file: '文件',
  uploaded: '上传时间',
  duty: '企微值守设置',
  onDuty: '本人正在值守',
  autoReply: '本人自动答复',
  dutyHint: '仅修改本人状态，不代表已经开通外部群消息读取或私聊自动发送。',
  saved: '设置已保存。',
  newTask: '新建业务任务',
  title: '任务标题',
  carrier: '执行载体',
  retries: '最大重试次数',
  retry: '重试任务',
  closeTask: '关闭任务',
  resolution: '处理说明',
  confirmClose: '确认关闭此任务？此操作将改变服务端任务状态。',
  more: '更多操作'
} as const
type Copy = { [K in keyof typeof zh]: string }
const en: Copy = {
  reminderCueTitle: 'Task reminder',
  reminderRepeatPrefix: 'No update for 30 minutes; please follow up · ',
  reminderRepeatHint: 'One follow-up alert after 30 minutes without a status update. Keep the client running and connected.',
  reminderSoundTest: 'Preview reminder sound',
  reminderSoundFailed: 'Sound could not play. Check volume and audio output, then preview again. Text alerts remain available.',
  copyReply: 'Copy reply',
  replyCopied: 'Copied',
  replyCopyFailed: 'Copy failed. Select the text and copy it manually.',
  suggestedReply: 'Suggested reply',
  currentReply: 'Current reply',
  followupReply: 'Follow-up reply',
  alternativeReply: 'Alternative reply',
  account: 'Account security',
  password: 'Change password',
  logout: 'Sign out',
  close: 'Close',
  cancel: 'Cancel',
  save: 'Save',
  refresh: 'Refresh',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  passwordHint:
    'Use at least 6 characters and a different password. The old saved password will be cleared; enable Remember password on your next sign-in.',
  passwordSaved: 'Password changed and current session renewed.',
  logoutHint: 'Sign out clears this session and saved credentials. Save unfinished work first.',
  working: 'Working…',
  failed: 'Unable to complete. Check connection and permissions, then retry.',
  unavailable: 'This feature is not enabled on the server.',
  dirty: 'Save or clear unfinished work before updating.',
  empty: 'No records.',
  loading: 'Fetching records…',
  followups: 'Receivables',
  create: 'Create',
  personalFollowups: 'My receivables',
  subject: 'Business / group name',
  team: 'Business team',
  amount: 'Amount (CNY)',
  receivableDate: 'Receivable date',
  expectedDate: 'Expected payment date',
  created: 'Created and synchronized to the reminder center.',
  followupHint:
    'Record a real receivable to schedule follow-ups. WeCom notifications require your own verified binding.',
  inspect: 'View and manage',
  status: 'Status',
  retryHint: 'Submission is unconfirmed. Refresh the list first; retrying the same request will not duplicate it.',
  retrySubmit: 'Retry submission',
  resetDraft: 'Clear draft',
  abandon: 'Abandon this retry',
  abandonHint:
    'Clearing the draft does not undo a record already created. Check the list before creating another record to avoid duplicates.',
  previous: 'Previous page',
  next: 'Next page',
  submitted: 'Submitted',
  pending: 'Pending',
  paid: 'Paid',
  cancelled: 'Cancelled',
  closed: 'Closed',
  waiting: 'Awaiting update',
  history: 'Reminder occurrences',
  deliveries: 'Notification delivery',
  time: 'Time',
  channel: 'Channel',
  attempts: 'Attempts',
  error: 'Error class',
  nextRetry: 'Next retry',
  historyHint: 'A triggered reminder is not proof that a notification was delivered.',
  uploads: 'Upload history',
  resume: 'Resume',
  rechunk: 'Rechunk',
  chunkSize: 'Characters per chunk',
  overlap: 'Overlap characters',
  rechunkHint:
    'Rechunking replaces the unsubmitted chunks. Preserve your edits first. The server rejects changes to submitted or published uploads.',
  file: 'File',
  uploaded: 'Uploaded',
  duty: 'WeCom duty settings',
  onDuty: 'I am on duty',
  autoReply: 'My automatic replies',
  dutyHint: 'Changes only your own state, not external-group access or private-message sending permissions.',
  saved: 'Settings saved.',
  newTask: 'Create business task',
  title: 'Task title',
  carrier: 'Execution carrier',
  retries: 'Maximum retries',
  retry: 'Retry task',
  closeTask: 'Close task',
  resolution: 'Resolution',
  confirmClose: 'Close this task? This changes the server task state.',
  more: 'More actions'
}
const ja: Copy = {
  ...en,
  reminderCueTitle: 'タスクリマインダー',
  reminderRepeatPrefix: '30分間更新がありません。フォローしてください · ',
  reminderRepeatHint: '初回通知後、状態の更新がなければ30分後に一度再通知します。クライアントを起動・接続したままにしてください。',
  reminderSoundTest: '通知音を試聴',
  reminderSoundFailed: '音声を再生できません。音量と出力機器を確認してください。テキスト通知は表示されます。',
  copyReply: 'コピー',
  replyCopied: 'コピーしました',
  replyCopyFailed: 'コピーできませんでした。文章を選択してコピーしてください。',
  suggestedReply: '回答案',
  currentReply: '現在の返信',
  followupReply: 'フォローアップ返信',
  alternativeReply: '別の回答案',
  account: 'アカウントの安全',
  password: 'パスワード変更',
  logout: 'ログアウト',
  close: '閉じる',
  cancel: 'キャンセル',
  save: '保存',
  refresh: '更新',
  currentPassword: '現在のパスワード',
  newPassword: '新しいパスワード',
  confirmPassword: 'パスワード確認',
  passwordHint:
    '6文字以上で現在と異なるパスワードを設定してください。保存済みの旧パスワードを削除します。次回ログイン時に保存し直してください。',
  passwordSaved: 'パスワードと現在のセッションを更新しました。',
  logoutHint: 'セッションと保存済み認証情報を削除します。未保存の作業を先に保存してください。',
  working: '処理中…',
  failed: '完了できませんでした。接続と権限を確認してください。',
  unavailable: 'サーバーで未有効の機能です。',
  dirty: '未保存の作業を保存または消去してから更新してください。',
  empty: '記録はありません。',
  loading: '記録を取得中…',
  followups: '売掛金フォロー',
  create: '新規作成',
  personalFollowups: '自分の売掛金',
  subject: '業務対象 / グループ名',
  team: '担当チーム',
  amount: '金額（人民元）',
  receivableDate: '売掛日',
  expectedDate: '入金予定日',
  created: '作成し、リマインダーに同期しました。',
  followupHint: '実際の売掛金からフォロー予定を作成します。WeCom通知には本人の連携が必要です。',
  inspect: '確認と処理',
  status: '状態',
  retryHint: '送信結果が未確認です。先に一覧を更新してください。同一リクエストの再試行では重複作成しません。',
  retrySubmit: '送信を再試行',
  resetDraft: '下書きを消去',
  abandon: '再試行を放棄',
  abandonHint:
    '下書きを消去しても作成済みの記録は取り消されません。重複を避けるため、新規作成の前に一覧を確認してください。',
  previous: '前のページ',
  next: '次のページ',
  submitted: '送信済み',
  pending: '処理待ち',
  paid: '入金済み',
  cancelled: '取消済み',
  closed: '終了',
  waiting: '更新待ち',
  history: 'リマインダー履歴',
  deliveries: '通知配信記録',
  time: '時刻',
  channel: 'チャネル',
  attempts: '試行回数',
  error: 'エラー種別',
  nextRetry: '次の再試行',
  historyHint: 'リマインダーの発火と通知の配信完了は異なります。',
  uploads: 'アップロード履歴',
  resume: '処理を再開',
  rechunk: '再分割',
  chunkSize: 'ブロック文字数',
  overlap: '重複文字数',
  rechunkHint: '未送信ブロックを置き換えます。編集を先に保全してください。送信・公開済みの変更はサーバーが拒否します。',
  file: 'ファイル',
  uploaded: 'アップロード日時',
  duty: 'WeCom当番設定',
  onDuty: '当番中',
  autoReply: '自分の自動返信',
  dutyHint: '本人の状態のみ変更します。外部グループの読取・私信送信の権限は付与しません。',
  saved: '設定を保存しました。',
  newTask: '業務タスク作成',
  title: 'タスク名',
  carrier: '実行先',
  retries: '最大再試行回数',
  retry: 'タスク再試行',
  closeTask: 'タスク終了',
  resolution: '処理説明',
  confirmClose: 'タスクを終了しますか？サーバーの状態が変わります。',
  more: 'その他の操作'
}
const hant: Copy = {
  ...zh,
  reminderCueTitle: '待辦提醒',
  reminderRepeatPrefix: '30 分鐘未更新，請繼續跟進 · ',
  reminderRepeatHint: '首次提醒後，狀態未更新將在 30 分鐘後補提醒一次。用戶端需保持執行並連線伺服器。',
  reminderSoundTest: '試聽提醒音',
  reminderSoundFailed: '提示音未播放，請檢查音量和音訊裝置後試聽。文字提醒不受影響。',
  copyReply: '點擊複製',
  replyCopied: '已複製',
  replyCopyFailed: '複製失敗，請選取文字後複製',
  suggestedReply: '回答建議',
  currentReply: '目前回覆話術',
  followupReply: '繼續跟進話術',
  alternativeReply: '備選回答',
  account: '帳戶安全',
  password: '修改密碼',
  logout: '登出',
  close: '關閉',
  cancel: '取消',
  save: '儲存',
  refresh: '重新整理',
  currentPassword: '目前密碼',
  newPassword: '新密碼',
  confirmPassword: '確認新密碼',
  passwordHint: '新密碼至少 6 位，且不能與目前密碼相同。修改後會清除本機儲存的舊密碼，下次登入請重新勾選記住密碼。',
  passwordSaved: '密碼已修改，目前工作階段已更新。',
  logoutHint: '登出會清除目前工作階段及本機記住的登入資訊。請先儲存未提交內容。',
  working: '處理中…',
  failed: '操作未完成，請檢查連線及權限後重試。',
  unavailable: '伺服器尚未啟用此功能。',
  dirty: '有未儲存內容或執行中的操作，請完成或清空後更新。',
  empty: '暫無記錄。',
  loading: '正在讀取記錄…',
  followups: '應收款跟進',
  create: '新增',
  personalFollowups: '我建立的應收款',
  subject: '業務對象 / 群組名稱',
  team: '業務團隊',
  amount: '應收金額（元）',
  receivableDate: '應收日期',
  expectedDate: '預計入帳日期',
  created: '已建立，提醒已同步至提醒中心。',
  followupHint: '記錄實際應收款，由伺服器建立後續提醒；企微通知需本人已完成綁定。',
  inspect: '檢視與處理',
  status: '狀態',
  retryHint: '未確認提交結果。請先重新整理列表；重試同一請求不會重複建立。',
  retrySubmit: '重試提交',
  resetDraft: '清空草稿',
  abandon: '放棄本次重試',
  abandonHint: '放棄只會清空本機草稿，不撤銷可能已建立的記錄。重新新增前請先核對列表，避免重複。',
  previous: '上一頁',
  next: '下一頁',
  submitted: '已提交',
  pending: '待處理',
  paid: '已收款',
  cancelled: '已取消',
  closed: '已關閉',
  waiting: '等待更新',
  history: '提醒觸發歷史',
  deliveries: '通知投遞記錄',
  time: '時間',
  channel: '管道',
  attempts: '嘗試次數',
  error: '錯誤類別',
  nextRetry: '下次重試',
  historyHint: '觸發記錄與通知送達是不同階段；不將已觸發顯示為已送達。',
  uploads: '歷史上傳',
  resume: '繼續處理',
  rechunk: '重新切分',
  chunkSize: '每塊字元數',
  overlap: '重疊字元數',
  rechunkHint: '重新切分將替換未提交分塊，請先保留編輯。已提交或發布的批次由伺服器拒絕修改。',
  file: '檔案',
  uploaded: '上傳時間',
  duty: '企微值守設定',
  onDuty: '本人正在值守',
  autoReply: '本人自動答覆',
  dutyHint: '僅修改本人狀態，不代表已開通外部群組讀取或私聊自動傳送。',
  saved: '設定已儲存。',
  newTask: '新增業務任務',
  title: '任務標題',
  carrier: '執行載體',
  retries: '最大重試次數',
  retry: '重試任務',
  closeTask: '關閉任務',
  resolution: '處理說明',
  confirmClose: '確認關閉任務？此操作會變更伺服器任務狀態。',
  more: '更多操作'
}
export function useDeliveryCopy(): Copy {
  const { locale } = useI18n()
  return ({ zh, en, ja, 'zh-hant': hant } as Record<string, Copy>)[locale] ?? en
}
